name: Render Awake

on:
  schedule:
    - cron: "*/14 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: ${{ secrets.WEBHOOK_HOST }}
