name: Render Awake

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.WEBHOOK_HOST }}
          method: POST
